

<br/>
<p>

	<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
  	<a data-toggle="collapse" href="#email" aria-expanded="false" aria-controls="email">
    	email
  	</a>
</p>

<div class="collapse" id="email">
 <div class="card card-block">
    <i>name</i> {dot} <i>surname</i> {at} um.edu.mt <br/>
  </div>
</div>

<p>
	<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
  	<a data-toggle="collapse" href="#address" aria-expanded="false" aria-controls="address">
    	address
  	</a>	
 </p>
 
 <div class="collapse" id="address">
 <div class="card card-block">
    Media and Knowledge Sciences Building, Rm 608, University of Malta<br/>
	Tal-Qroqq Msida MSD2080, Malta<br />
  </div>
</div>

<p>
	<span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span>
  	<a data-toggle="collapse" href="#phoneno" aria-expanded="false" aria-controls="phoneno">
    	landline
  	</a>	
 </p>

<div class="collapse" id="phoneno">
 <div class="card card-block">
    (+356) 2340 2150
  </div>
</div>

<!-- <p>
	<a target=_blank href="http://www.um.edu.mt/linguistics/">Institute of Linguistics and Language Technology</a>
</p>

<p>
	<a target=_blank href="http://aclweb.org/aclwiki/index.php?title=SIGGEN">SIGGEN</a>
</p>
 -->
