<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>MASRI - Maltese Automatic Speech Recognition</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  <!-- =======================================================
  * Template Name: Regna - v2.0.0
  * Template URL: https://bootstrapmade.com/regna-bootstrap-onepage-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>
  <main id="main">
    <section>
      <div class="container">
        <h1>MASRI - Maltese Automatic Speech Recognition</h1>        
        <h2>Thank you. Please choose your downloads below.</h2>

        <table class="table">
          <thead>
            <th>Dataset</th>
            <th>Size</th>
            <th>Type</th>
            <th>Link</th>
          </thead>
          <tbody>
            <tr>
              <td>MASRI-Headset v2</td><td>6h39m</td><td>Read speech</td><td><a target=_blank class="btn btn-primary" role="button" href="https://drive.google.com/file/d/1fNjXYUQmXXV6q-A18zq6BTjxtjZeUhXE/view?usp=sharing">Download</a></td>
            </tr>
            <tr>
              <td>MASRI-Farfield</td><td>9h37m</td><td>Read speech</td><td><a target=_blank class="btn btn-primary" role="button" href="https://drive.google.com/file/d/1m0uGzxUf7gcJLhnodq2lrKZJvZcnlz0F/view?usp=sharing">Download</a></td>
            </tr>
            <tr>
              <td>MASRI-Booths</td><td>2h27m</td><td>Read speech</td><td><a target=_blank class="btn btn-primary" role="button" href="https://drive.google.com/file/d/1Og9Kz-N2EtRfp5Say3A10Rz_JM-E_Hq5/view?usp=sharing">Download</a></td>
            </tr>
            <tr>
              <td>MASRI-MEP</td><td>1h17m</td><td>Spontaneous speech</td><td><a target=_blank class="btn btn-primary" role="button" href="https://drive.google.com/file/d/1qcB6it3TQw0be0ZAzELz-oy0oFoBmoaC/view?usp=sharing">Download</a></td>
            </tr>
            <tr>
              <td>MASRI-COMVO</td><td>7h29m</td><td>Read speech</td><td><a target=_blank class="btn btn-primary" role="button" href="https://drive.google.com/file/d/1AMFIq5dJOvANsmkJjjRZrZ8F64yrxA2_/view?usp=sharing">Download</a></td>
            </tr>
            <tr>
              <td>MASRI-TUBE</td><td>13h17m</td><td>Spontaneous speech</td><td><a target=_blank class="btn btn-primary" role="button" href="https://drive.google.com/file/d/130XaeiKoXPMdkv-L9fk3TLVLhVzPu8AO/view?usp=sharing">Download</a></td>
            </tr>
            <tr>
              <td>MASRI-Synthetic</td><td>99h18m</td><td>Synthesized speech</td><td><a target=_blank class="btn btn-primary" role="button" href="https://drive.google.com/file/d/1NL5zHuq3pR9K3EnuWfCn-LtwhALdIQhU/view?usp=sharing">Download</a></td>
            </tr>
            <tr>
              <td>MASRI-Dev</td><td>1h</td><td>Spontaneous speech</td><td><a target=_blank class="btn btn-primary" role="button" href="https://drive.google.com/file/d/1Qa2DT-FqQbmOXbbJSMUa-KGdrXrrSv2Q/view?usp=sharing">Download</a></td>
            </tr>
            <tr>
              <td>MASRI-Test</td><td>1h</td><td>Spontaneous speech</td><td><a target=_blank class="btn btn-primary" role="button" href="https://drive.google.com/file/d/1U2YNwg2-vmThs_dhZd7xhGAmcf1eKC5P/view?usp=sharing">Download</a></td>
            </tr>
          </tbody>
        </table>  

        <p>
        Click <a href="https://www.um.edu.mt/projects/masri/">here</a> to return to the MASRI pages.
        </p>
      </div>
    </section>
</body>
</html>                     
                      