<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>                        
			</button>
			<a class="navbar-brand" href="./index.php">Albert Gatt</a>
		</div>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav">
				<!-- <li></li> -->
				<li><a href="./projects.php">Projects</a></li>
				<li><a href="./publications.php">Publications</a></li>
				<li><a href="./resources.php">Resources</a></li>
				<li><a href="./team.php">Research team</a></li>
				<li><a href="./teaching.php">Teaching</a></li>
				<li><a href="./activities.php">Activities</a></li>	
				<li><a href="./media.php">Media</a></li>				
			</ul>
			<!-- <ul class="nav navbar-nav navbar-right">
				<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
			</ul> -->
		</div>
	</div>