<h2>Stqarrija</h2>
<p>Jien, Alison Farrugia, studenta fl-Universita’ ta' Malta u qed
	insegwi l-kors ta B.Sc. (Unuri) fit- Teknoloġija tal-Lingwa Umana.
	Għat-teżi tiegħi għandi bżonn kelliema nattivi tal-Malti biex jimlew
	dan il-kwestjonarju. Il-mistoqsijiet ser jibqgħu anonimi u jistgħu
	jitwaqqfu fi kwalunkwe ħin għad-dispożizzijoni tal-parteċipant.</p>

<p>
	Dan l-istudju qed isir taħt is-superviżjoni ta' <a
		href="http://staff.um.edu.mt/albert.gatt" target=_BLANK>Dr Albert Gatt</a>,
	fi ħdan l-<a href="http://www.um.edu.mt/linguistics">Istitut
		tal-Lingwistika, l-Università ta' Malta</a>. Għal aktar informazzjoni,
	tista' tikkuntattja lil Alison Farrugia fuq: <i>alison.farrugia.14@um.edu.mt</i>.
</p>

<div class="col-md-6">
	<h2>Istruzzjonijiet</h2>

	<p>Il-parteċipant/a ħa jkollu/jkollha diversi stampi quddiemu/a fejn
		ser jkun hemm żewġ oġġetti mmarkati b’kaxxi. Huwa/Hija mitlub/a li
		jagħżel/tagħżel mill-għażla mogħtija, dik il-kelma li hi l-iktar
		addattata sabiex tiddeskrivi r-relazzjoni bejn dawn l-oġġetti. Meta
		titlesta stampa il-parteċipant/a huwa/hija mitlub/a li jsegwi/ssegwi
		għall-istampa li jmiss. L-esperiment jista' jitwaqqaf fi kwalunkwe
		ħin, għad-diżposizzijoni tal-parteċipant.</p>
	<p>Qabel tkompli, nixtiequ nitolbuk ftit informazzjoni, li se tinżamm
		kunfidenzjali.</p>
	<p>Jekk jogħġbok, wieġeb għad-domandi fuq din il-paġna, imbagħad
		kompli.</p>

</div>

<div class="col-md-6">
	<h2>Informazzjoni dwarek</h2>

	<form method="POST" action="index.php" name="subjectform"
		id="subjectform">
		<input type="hidden" name="page" value="newsubject" />
		<fieldset class="form-group row">
			<legend class="col-form-legend col-sm-2">Sess</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<label class="form-check-label"> <input class="form-check-input"
						type="radio" name="gender" id="gender1" value="female" required>
						Mara
					</label>
				</div>
				<div class="form-check">
					<label class="form-check-label"> <input class="orm-check-input"
						type="radio" name="gender" id="gender2" value="male"> Raġel
					</label>
				</div>
			</div>
		</fieldset>

		<fieldset class="form-group row">
			<legend class="col-form-legend col-sm-2">Età</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<label class="form-check-label"> <input class="form-check-input"
						type="radio" name="age" id="age1" value="1" required> Inqas minn
						18-il sena
					</label>
				</div>
				<div class="form-check">
					<label class="form-check-label"> <input class="form-check-input"
						type="radio" name="age" id="age2" value="2"> Bejn 18 u 25 sena
					</label>
				</div>
				<div class="form-check">
					<label class="form-check-label"> <input class="form-check-input"
						type="radio" name="age" id="age3" value="3"> Bejn 26 u 35 sena
					</label>
				</div>
				<div class="form-check">
					<label class="form-check-label"> <input class="form-check-input"
						type="radio" name="age" id="age4" value="4"> Bejn 36 u 50 sena
					</label>
				</div>
				<div class="form-check">
					<label class="form-check-label"> <input class="form-check-input"
						type="radio" name="age" id="age5" value="5"> 'Il fuq minn 50 sena
					</label>
				</div>
			</div>
		</fieldset>

		<fieldset class="form-group row">
			<legend class="col-form-legend col-sm-2">Student/a</legend>
			<div class="col-sm-10">
				<div class="form-check">
					<label class="form-check-label"> <input class="form-check-input"
						type="radio" name="student" id="student1" value="uni" required>
						Student/a l-università
					</label>
				</div>
				<div class="form-check">
					<label class="form-check-label"> <input class="form-check-input"
						type="radio" name="student" id="student2" value="jc"> Student/a
						l-Junior College
					</label>
				</div>
				<div class="form-check">
					<label class="form-check-label"> <input class="form-check-input"
						type="radio" name="student" id="student3" value="ns"> Mhux
						student/a
					</label>
				</div>
			</div>
		</fieldset>

		<p class="lead">
			Jekk tagħfas il-buttuna ta' hawn taħt, tkun qed tindika li taqbel ma' <a href="#" data-toggle="modal" data-target="#consent">dawn il-kundizzjonijiet</a> dwar l-użu tal-informazzjoni miġbura f'dan l-istudju.
		</p>

		

<div class="modal fade" id="consent" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Agħlaq"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Kundizzjonijiet</h4>
      </div>
      <div>
	<p>
        Din ir-riċerka hija mmexxija bħala parti mit-teżi ta’ <a href="mailto:alison.farrugia.14@um.edu.mt">Alison Farrugia</a>, li tistudja fl-Istitut tal-Lingwistika fl-Universita’ ta’ Malta taħt is-superviżjoni ta’ <a href="mailtp:albert.gatt@um.edu.mt">Dr. Albert Gatt</a>. 
	</p>
	<p>
Taħt l-Att tal-Protezzjoni tad-Data, jien għandi kull dritt li nitlob l-informazzjoni li ġiet miġbura matul din ir-riċerka u nista’ ukoll nirrikjedi li titħassar l-informazzjoni tiegħi f’kwalunkwe ħin matul dan l-esperiment.</p>
<p>
Jien għandi kull dritt sabiex nieqaf mill-esperiment fi kwalunkwe mument matul ir-riċerka u mingħajr ma jkolli għalfejn nagħti ebda raġuni. 
</p>

<p>
M’hawn ebda riskji f’dan l-istudju u l-informazzjoni tiegħi se tibqa’ anonima.
</p>
<p>
Jien qiegħed/qiegħda nagħti l-kunsens tiegħi lil Alison Farrugia, li għandha l-permess tiegħi sabiex tuża l-informazzjoni li nagħti permezz ta' dan l-esperiment.
</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Agħlaq</button>
      </div>
    </div>
  </div>
</div>

		<input class="btn btn-primary" type="submit" name="continue"
			value="Ibda l-esperiment" />

	</form>

</div>
